### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by xipengshen** [Xuhpclab/jxperf#110]
When running the 'make' command, the following error appeared:

=========
.... 
g++ -Wunused-but-set-variable -m64 -O3 -fPIC  -Wall -DUSE_BOOST_UNORDERED_CONTAINER -DENABLE_CALL_PATH_COLLECTION  -I/home/xshen5/Research/PetalMem/Code/jdk-17.0.1/include -I/home/xshen5/Research/PetalMem/Code/jdk-17.0.1/include/linux -I./external/hpctoolkit/lib/prof-lean -I./external/hpctoolkit -I./util -I./util/arch/x86-family -I/home/xshen5/Research/PetalMem/Code/jxperf/src/../build/thirdparty/include -I./profiler -I./perf -I./util -I./util/arch -I./util/arch/x86-family -std=c++11 -MMD -c -o /home/xshen5/Research/PetalMem/Code/jxperf/src/../build/./profiler/profiler.o profiler/profiler.cpp 
profiler/profiler.cpp:7:10: fatal error: numa.h: No such file or directory
 #include <numa.h>
          ^~~~~~~~
compilation terminated.
Makefile:43: recipe for target '/home/xshen5/Research/PetalMem/Code/jxperf/src/../build/./profiler/profiler.o' failed
make[1]: *** [/home/xshen5/Research/PetalMem/Code/jxperf/src/../build/./profiler/profiler.o] Error 1
make[1]: Leaving directory '/home/xshen5/Research/PetalMem/Code/jxperf/src'
Makefile:6: recipe for target 'thirdparty' failed
make: *** [thirdparty] Error 2
========
> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic

> uname -a
Linux eb2-3226-lin13 4.15.0-161-generic #169-Ubuntu SMP Fri Oct 15 13:41:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

> g++ --version
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by xl10** [comment]
Please install libnuma first using apt-get. The tool needs libnuma to measure numa-related issues.

**Comment by xipengshen** [comment]
I figured it out. It could help to be mentioned in the installation instruction.
