### ISSUE TITLE
README typo

### ISSUE THREAD

**Issue by xipengshen** [Xuhpclab/jxperf#111]
In README, the following command 

$ LD_PRELOAD=$JXPerf_HOME/build/libpreload.so java -javaagent:$JAVA_AGENT -agentpath:$JXPerf_HOME/build/libagent.so=DataCentric::MEM_LOAD_UOPS_RETIRED:L1_MISS:precise=2@<sampling rate> -cp <classpath> <java program>

should be replaced with (the path of the libpreload.so is wrong): 

$ LD_PRELOAD=$JXPerf_HOME/build/preload/libpreload.so java -javaagent:$JAVA_AGENT -agentpath:$JXPerf_HOME/build/libagent.so=DataCentric::MEM_LOAD_UOPS_RETIRED:L1_MISS:precise=2@<sampling rate> -cp <classpath> <java program>

**Comment by bolunli11** [comment]
I'm sorry for the confusion. Will update with the correct path in readme.
