### ISSUE TITLE
Executing the Tool

### ISSUE THREAD

**Issue by xipengshen** [Xuhpclab/jxperf#112]
When trying to run the tool in the provided benchmark folder, the following results showed up:

------------
jxperf/benchmark$ ./run.sh
the current event name: CYCLES:precise=2
Cannot create a single watch point

jxperf/benchmark$ python3.9 $JXPerf_HOME/script/process_raw_data.py
Traceback (most recent call last):
  File "/home/xshen5/Research/PetalMem/Code/jxperf/script/process_raw_data.py", line 397, in <module>
    main()
  File "/home/xshen5/Research/PetalMem/Code/jxperf/script/process_raw_data.py", line 268, in main
    if result[0] == 'DATACENTRIC':
IndexError: list index out of range
--------------

Note, the path of the preload library in run.sh was fixed before running the commands.

**Comment by bolunli11** [comment]
Hi Xipeng,

Seems that you can run our tool (./run.sh runs successfully), but you got problem when using python to process data offline.

Let's go through the running process in two steps:

1. Run JXPerf:
    1.1. Go to benchmark folder
    1.2. Use command to run with CPU Cycle mode: 
```LD_PRELOAD=$JXPerf_HOME/build/preload/libpreload.so java -agentpath:$JXPerf_HOME/build/libagent.so=Generic::CYCLES:precise=2@1000000 -jar ./dacapo.jar lusearch```
    1.3. After running above command, there's a file named "agent-statistics.run" would be generated. Could you please cope&paste its contents here?

2. Offline process:
    2.1. Without VS code GUI, using command: ```$JXPerf_HOME/script/process_raw_data.py```
(I used python 3.8.11, but I believe python 3.9 also works)
    2.2. With VS code GUI, using command: ```$JXPerf_HOME/script/process_raw_data_to_vscode.py $JXPerf_HOME/benchmark/lucene```
Then a file named "test.drcctprof" would be generated. To check this file, using command: ```code test.drcctprof```

**Comment by xipengshen** [comment]
The content of agent-statistics.run is empty. 


jxperf/benchmark$ LD_PRELOAD=$JXPerf_HOME/build/preload/libpreload.so java -agentpath:$JXPerf_HOME/build/libagent.so=Generic::CYCLES:precise=2@1000000 -jar ./dacapo.jar lusearch
the current event name: CYCLES:precise=2
Cannot create a single watch point
jxperf/benchmark$ cat agent-statistics.run

**Comment by bolunli11** [comment]
Normally, the agent-statistics.run should not be empty. How about other .run files, are they all empty as well?

From my running output, I didn't see the message "Cannot create a single watch point". So I suspect the reason is the environment doesn't support hardware watchpoint, which is a feature our tool needs to use. 

The environment I'm using is Ubuntu, version 20.04 (machine is ```eb2-3224-lin00.csc.ncsu.edu```). Can I know what's your environment?

**Comment by xipengshen** [comment]
I was on eb2-3226-lin13. Its cpu is Intel(R) Xeon(R) CPU E5-2623 v4 @ 2.60GHz. OS info as follows:

---------------
(base) xshen5@eb2-3226-lin13:~/Research/PetalMem/Code/jxperf/benchmark$ lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
(base) xshen5@eb2-3226-lin13:~/Research/PetalMem/Code/jxperf/benchmark$ uname -a
Linux eb2-3226-lin13 4.15.0-161-generic #169-Ubuntu SMP Fri Oct 15 13:41:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

-----------

**Comment by bolunli11** [comment]
It seems that your environment supports watchpoint. Anyway, I just updated the repo to turn off the watchpoint. Please get the latest code.

Also, since cpu cycles is not that useful, if you want to monitor objects, please use below commands:

1. Running command: open run.sh and use the command in section 2 Data-centric
2. Offline process command: ```$JXPerf_HOME/script/process_raw_data.py```

To reduce the runtime overhead, our tool only monitors objects whose size are larger or equal to 1024kb. If you want to monitor every object, please go to file /thirdparty/allocation-instrumenter/src/main/java/com/google/monitoring/runtime/instrumentation/AllocationInstrumenter.java, and change the default 1024 to any size at line 173. After the changing, you need to recompile the code (make clean & make).

**Comment by xipengshen** [comment]
The updated version gave the following errors when running the following command: 

>benchmark$  LD_PRELOAD=$JXPerf_HOME/build/preload/libpreload.so java -javaagent:$JXPerf_HOME/thirdparty/allocation-instrumenter/target/java-allocation-instrumenter-HEAD-SNAPSHOT.jar -agentpath:$JXPerf_HOME/build/libagent.so=DataCentric::MEM_LOAD_UOPS_RETIRED:L1_MISS:precise=2@10000 -jar ./dacapo.jar -s large lusearch

--------------
the current event name: MEM_LOAD_UOPS_RETIRED:L1_MISS:precise=2
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
Jan 02, 2022 5:42:02 PM com.google.monitoring.runtime.instrumentation.AllocationInstrumenter instrument
WARNING: Failed to instrument class.
java.lang.IllegalArgumentException: Unsupported class file major version 61
	at com.google.monitoring.runtime.instrumentation.asm.ClassReader.<init>(ClassReader.java:195)
	at com.google.monitoring.runtime.instrumentation.asm.ClassReader.<init>(ClassReader.java:176)
	at com.google.monitoring.runtime.instrumentation.asm.ClassReader.<init>(ClassReader.java:162)
	at com.google.monitoring.runtime.instrumentation.AllocationInstrumenter.instrument(AllocationInstrumenter.java:361)
	at com.google.monitoring.runtime.instrumentation.AllocationInstrumenter.instrument(AllocationInstrumenter.java:389)
	at com.google.monitoring.runtime.instrumentation.AllocationInstrumenter.transform(AllocationInstrumenter.java:343)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)
	at java.base/java.lang.WeakPairMap$Pair.weak(WeakPairMap.java:201)
	at java.base/java.lang.WeakPairMap.putIfAbsent(WeakPairMap.java:123)
	at java.base/java.lang.Module.implAddReads(Module.java:488)
	at java.base/java.lang.Module.implAddReads(Module.java:449)
	at java.base/java.lang.System$2.addReads(System.java:2335)
	at java.base/jdk.internal.module.Modules.addReads(Modules.java:90)
	at java.base/jdk.internal.module.Modules.transformedByAgent(Modules.java:193)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:169)
	at com.google.monitoring.runtime.instrumentation.AllocationInstrumenter.bootstrap(AllocationInstrumenter.java:309)
	at com.google.monitoring.runtime.instrumentation.AllocationInstrumenter.premain(AllocationInstrumenter.java:278)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.google.monitoring.runtime.instrumentation.AllocationInstrumenterBootstrap.premain(AllocationInstrumenterBootstrap.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
-------------

**Comment by bolunli11** [comment]
It might be the jdk version's problem, could you try JDK11.0.5 and see if you still have this issue?

**Comment by xipengshen** [comment]
After changing JDK to 11.0.5, the benchmark seems running, but then gave out an error: 

---------
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f38b43c1763, pid=22540, tid=22571
#
# JRE version: Java(TM) SE Runtime Environment (11.0.5+10) (build 11.0.5+10-LTS)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (11.0.5+10-LTS, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libagent.so+0x32763]  PerfManager::closeEvents()+0x73
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /home/xshen5/Research/PetalMem/Code/jxperf/benchmark/core.22540)
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -javaagent:/home/xshen5/Research/PetalMem/Code/jxperf/thirdparty/allocation-instrumenter/target/java-allocation-instrumenter-HEAD-SNAPSHOT.jar -agentpath:/home/xshen5/Research/PetalMem/Code/jxperf/build/libagent.so=DataCentric::MEM_LOAD_UOPS_RETIRED:L1_MISS:precise=2@10000 ./dacapo.jar -s large lusearch

Host: Intel(R) Xeon(R) CPU E5-2623 v4 @ 2.60GHz, 8 cores, 15G, Ubuntu 18.04.6 LTS
Time: Sun Jan  2 19:55:31 2022 EST elapsed time: 7 seconds (0d 0h 0m 7s)

---------------  T H R E A D  ---------------

Current thread (0x00007f38b2233800):  JavaThread "Query6" [_thread_in_native, id=22571, stack(0x00007f385d702000,0x00007f385d803000)]

Stack: [0x00007f385d702000,0x00007f385d803000],  sp=0x00007f385d8019d0,  free space=1022k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libagent.so+0x32763]  PerfManager::closeEvents()+0x73


siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000004

Register to memory mapping:

RAX=0x0 is NULL
RBX=0x0 is NULL
RCX=0x00007f38b7070320: <offset 0x000000000021a320> in /lib/x86_64-linux-gnu/libpthread.so.0 at 0x00007f38b6e56000
RDX=0x00007f385d802a30 is pointing into the stack for thread: 0x00007f38b2233800
RSP=0x00007f385d8019d0 is pointing into the stack for thread: 0x00007f38b2233800
RBP=0x0 is NULL
RSI=0x0000000000000001 is an unknown value
RDI=0x0000000000000020 is an unknown value
R8 ={method} {0x00007f385e34f848} 'exit' '()V' in 'java/lang/Thread'
R9 =0x0000000000000001 is an unknown value
R10=0x000000000000000d is an unknown value
R11=0x00007f38b43c16f0: _ZN11PerfManager11closeEventsEv+0x0000000000000000 in /home/xshen5/Research/PetalMem/Code/jxperf/build/libagent.so at 0x00007f38b438f000
R12=0x00007f3808001bf0 points into unknown readable memory: 00 00 00 00 00 00 00 00
R13=0x00007f38b0022520 points into unknown readable memory: c0 58 5d b6 38 7f 00 00
R14=0x00007f385d801b00 is pointing into the stack for thread: 0x00007f38b2233800
R15=0x00007f385d801ae0 is pointing into the stack for thread: 0x00007f38b2233800


Registers:
RAX=0x0000000000000000, RBX=0x0000000000000000, RCX=0x00007f38b7070320, RDX=0x00007f385d802a30
RSP=0x00007f385d8019d0, RBP=0x0000000000000000, RSI=0x0000000000000001, RDI=0x0000000000000020
R8 =0x00007f385e34f848, R9 =0x0000000000000001, R10=0x000000000000000d, R11=0x00007f38b43c16f0
R12=0x00007f3808001bf0, R13=0x00007f38b0022520, R14=0x00007f385d801b00, R15=0x00007f385d801ae0
RIP=0x00007f38b43c1763, EFLAGS=0x0000000000010246, CSGSFS=0x002b000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007f385d8019d0)
0x00007f385d8019d0:   00007f38b2233800 00007f385d801ba0
0x00007f385d8019e0:   00007f3808000e20 00007f38b43bd38b
0x00007f385d8019f0:   00007f38b45d3b80 0000000000000000
0x00007f385d801a00:   0000000000000000 0000000000000000 

Instructions: (pc=0x00007f38b43c1763)
0x00007f38b43c1743:   8b 2c 24 8b 05 9c 2b 21 00 85 c0 74 37 31 db 66
0x00007f38b43c1753:   0f 1f 44 00 00 89 d8 48 8d 04 40 48 8d 6c c5 00
0x00007f38b43c1763:   8b 7d 04 85 ff 78 05 e8 e1 a6 fd ff 48 8b 7d 08
0x00007f38b43c1773:   83 c3 01 e8 15 94 fd ff 39 1d 67 2b 21 00 49 8b 

Stack slot to memory mapping:
stack at sp + 0 slots: 0x00007f38b2233800 is a thread
stack at sp + 1 slots: 0x00007f385d801ba0 is pointing into the stack for thread: 0x00007f38b2233800
stack at sp + 2 slots: 0x00007f3808000e20 points into unknown readable memory: 00 38 23 b2 38 7f 00 00
stack at sp + 3 slots: 0x00007f38b43bd38b: _ZN8Profiler9threadEndEv+0x000000000000072b in /home/xshen5/Research/PetalMem/Code/jxperf/build/libagent.so at 0x00007f38b438f000
stack at sp + 4 slots: 0x00007f38b45d3b80: _ZN8Profiler9_instanceE+0x0000000000000000 in /home/xshen5/Research/PetalMem/Code/jxperf/build/libagent.so at 0x00007f38b438f000
stack at sp + 5 slots: 0x0 is NULL
stack at sp + 6 slots: 0x0 is NULL
stack at sp + 7 slots: 0x0 is NULL


---------------  P R O C E S S  ---------------
Threads class SMR info:
_java_thread_list=0x00007f3848521080, length=17, elements={
0x00007f38b0033000, 0x00007f38b028d800, 0x00007f38b0291800, 0x00007f38b02a4000,
0x00007f38b02a6800, 0x00007f38b02a8800, 0x00007f38b02aa800, 0x00007f38b0360800,
0x00007f38b11cc000, 0x00007f38b2229800, 0x00007f38b222a800, 0x00007f38b222c000,
0x00007f38b222e000, 0x00007f38b2230000, 0x00007f38b2231800, 0x00007f38b2233800,
0x00007f38b2235000
}

Java Threads: ( => current thread )
  0x00007f38b0033000 JavaThread "main" [_thread_blocked, id=22541, stack(0x00007f38b739b000,0x00007f38b749c000)]
  0x00007f38b028d800 JavaThread "Reference Handler" daemon [_thread_blocked, id=22548, stack(0x00007f3884663000,0x00007f3884764000)]
  0x00007f38b0291800 JavaThread "Finalizer" daemon [_thread_blocked, id=22549, stack(0x00007f3884562000,0x00007f3884663000)]
  0x00007f38b02a4000 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=22550, stack(0x00007f3884183000,0x00007f3884284000)]
  0x00007f38b02a6800 JavaThread "C2 CompilerThread0" daemon [_thread_blocked, id=22551, stack(0x00007f3884082000,0x00007f3884183000)]
  0x00007f38b02a8800 JavaThread "C1 CompilerThread0" daemon [_thread_blocked, id=22552, stack(0x00007f385feff000,0x00007f3860000000)]
  0x00007f38b02aa800 JavaThread "Sweeper thread" daemon [_thread_blocked, id=22553, stack(0x00007f385fdfe000,0x00007f385feff000)]
  0x00007f38b0360800 JavaThread "Common-Cleaner" daemon [_thread_blocked, id=22554, stack(0x00007f385fcfd000,0x00007f385fdfe000)]
  0x00007f38b11cc000 JavaThread "Service Thread" daemon [_thread_blocked, id=22563, stack(0x00007f385e96f000,0x00007f385ea70000)]
  0x00007f38b2229800 JavaThread "Query0" [_thread_in_native, id=22565, stack(0x00007f385dd08000,0x00007f385de09000)]
  0x00007f38b222a800 JavaThread "Query1" [_thread_in_vm_trans, id=22566, stack(0x00007f385dc07000,0x00007f385dd08000)]
  0x00007f38b222c000 JavaThread "Query2" [_thread_in_Java, id=22567, stack(0x00007f385db06000,0x00007f385dc07000)]
  0x00007f38b222e000 JavaThread "Query3" [_thread_in_Java, id=22568, stack(0x00007f385da05000,0x00007f385db06000)]
  0x00007f38b2230000 JavaThread "Query4" [_thread_in_Java, id=22569, stack(0x00007f385d904000,0x00007f385da05000)]
  0x00007f38b2231800 JavaThread "Query5" [_thread_in_Java, id=22570, stack(0x00007f385d803000,0x00007f385d904000)]
=>0x00007f38b2233800 JavaThread "Query6" [_thread_in_native, id=22571, stack(0x00007f385d702000,0x00007f385d803000)]
  0x00007f38b2235000 JavaThread "Query7" [_thread_in_Java, id=22572, stack(0x00007f385d601000,0x00007f385d702000)]

Other Threads:
  0x00007f38b0285800 VMThread "VM Thread" [stack: 0x00007f3884766000,0x00007f3884866000] [id=22547]
  0x00007f38b1d71000 WatcherThread [stack: 0x00007f385de0b000,0x00007f385df0b000] [id=22564]
  0x00007f38b005a800 GCTaskThread "GC Thread#0" [stack: 0x00007f3895a2e000,0x00007f3895b2e000] [id=22542]
  0x00007f3874002800 GCTaskThread "GC Thread#1" [stack: 0x00007f385f3d2000,0x00007f385f4d2000] [id=22557]
  0x00007f3874004000 GCTaskThread "GC Thread#2" [stack: 0x00007f385f2d0000,0x00007f385f3d0000] [id=22558]
  0x00007f3874005800 GCTaskThread "GC Thread#3" [stack: 0x00007f385f1ce000,0x00007f385f2ce000] [id=22559]
  0x00007f3874007800 GCTaskThread "GC Thread#4" [stack: 0x00007f385f0cc000,0x00007f385f1cc000] [id=22560]
  0x00007f3874009000 GCTaskThread "GC Thread#5" [stack: 0x00007f385efca000,0x00007f385f0ca000] [id=22561]
  0x00007f387491d800 GCTaskThread "GC Thread#6" [stack: 0x00007f385d501000,0x00007f385d601000] [id=22573]
  0x00007f387491f000 GCTaskThread "GC Thread#7" [stack: 0x00007f385d3ff000,0x00007f385d4ff000] [id=22574]
  0x00007f38b00b8800 ConcurrentGCThread "G1 Main Marker" [stack: 0x00007f389408a000,0x00007f389418a000] [id=22543]
  0x00007f38b00ba800 ConcurrentGCThread "G1 Conc#0" [stack: 0x00007f3887a74000,0x00007f3887b74000] [id=22544]
  0x00007f3880001000 ConcurrentGCThread "G1 Conc#1" [stack: 0x00007f385eec8000,0x00007f385efc8000] [id=22562]
  0x00007f38b01ba000 ConcurrentGCThread "G1 Refine#0" [stack: 0x00007f388516a000,0x00007f388526a000] [id=22545]
  0x00007f38b01bc000 ConcurrentGCThread "G1 Young RemSet Sampling" [stack: 0x00007f3885068000,0x00007f3885168000] [id=22546]
... 
--------

**Comment by bolunli11** [comment]
I can't reproduce this error. I suspect the reason could be your machine doesn't support PMU sampling. You can check this by command ```cat /proc/sys/kernel/perf_event_paranoid```. If the result is 2, then it means the PMU sampling is turned off in your environment. You can turn it on using command ```sysctl -w kernel.perf_event_paranoid=1```

**Comment by xipengshen** [comment]
The output is not 2 but 3. Does it mean that the PMU sampling is on? 

>cat /proc/sys/kernel/perf_event_paranoid
3

**Comment by xipengshen** [comment]
After running "sysctl -w kernel.perf_event_paranoid=1", the tool worked. 
It might help other users it we put these tips into the README.

**Comment by bolunli11** [comment]
Yes, it's necessary to mention this in README.

BTW, the larger of value perf_event_paranoid, the less permission you have. To grant the PMU sampling permission, we keep this value less than 2 (0 or 1).

**Comment by xipengshen** [comment]
The issue is fixed. Some modifications will be made to the README.
