### ISSUE TITLE
Other installation notes

### ISSUE THREAD

**Issue by xipengshen** [Xuhpclab/jxperf#113]
In my installation, I had to install the following Python modules: 

pip install bintrees
pip install --upgrade google-api-python-client

Mentioning them in the README might help others.

**Comment by xl10** [comment]
Thank you, Xipeng. Our readme is not up-to-date. Will get a better readme.

**Comment by bolunli11** [comment]
Thanks for the suggestions, I'll mention these third-party packages in readme.
